#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-network-policy - DO280-OCP4
#       Configuring Network Policies
#
# SYNOPSIS
#     lab-network-policy {start|finish}
#
#        start  - prepare the system for starting the lab
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the Configuring Network Policies guided exercise.
#
# CHANGELOG
#   * Wed Sep 30 2020 James Mighion <jmighion@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin

# This defines which subcommands are supported (start, grade, etc.).
# Usually GEs do not have a grade verb
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='network-policy'
title='Guided Exercise: Configuring Network Policies'
# Do not change these variables
target='workstation'
run_as_root='true'


function lab_start {

  ocp4_print_prereq_header
  ocp4_is_cluster_up
  ocp4_login_as_admin
  ocp4_fail_if_project_exists "${this}" network-test

  ocp4_exit_on_failure "It looks like you have already started this exercise. To try this exercise again, run 'lab ${this} finish' followed by 'lab ${this} start'."

  ocp4_print_setup_header
  ocp4_add_standard_users
  ocp4_add_self_provisioing

  print_line ' Preparing Workstation:'
  ocp4_grab_lab_files

  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header
  ocp4_login_as_admin

  ocp4_delete_project "${this}" network-test

  if oc get namespaces -l network.openshift.io/policy-group=ingress -o name | grep -w "namespace/default"
  then
    pad2 "Remove network.openshift.io/policy-group=ingress label from the default project"
    if oc label namespace default network.openshift.io/policy-group-
    then
      print_SUCCESS
    else
      print_FAIL
    fi
  fi
  ocp4_cleanup_lab_files
  ocp4_print_cleanup_footer
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/labtool.do280.shlib

grading_main_program "$@"
