#!/bin/bash
#
# Copyright 2020 Red Hat, Inc.
#
# NAME
#     lab-auth-rbac - lab script for DO280-OCP4
#                          RBAC Guided Exercise
#
# SYNOPSIS
#     lab-auth-rbac {start|finish}
#
#        start  - prepare the system for starting the lab
#        finish - perform post-lab finish
#
# DESCRIPTION
#     This script, based on singular argument, either does start or finish for
#     the [name of the exercise]
#
# CHANGELOG
#   * Mon Sep 21 2020 Michael Phillips <miphilli@redhat.com>
#   - Renamed from lab-authorization-rbac to lab-auth-rbac based on moving to ch03.
#   * Thu Aug 20 2020 Michael Phillips <miphilli@redhat.com>
#   - added the ocp4_login_as_admin function to the lab_start function
#   * Fri Sep 20 2019 Iván Chavero <ichavero@redhat.com>
#   - initial creation


PATH=/usr/bin:/bin:/usr/sbin:/sbin:/root/bin:/usr/local/bin
declare -a valid_commands=(start finish)

# Change these variables to match your exercise
this='auth-rbac'
title='Guided Exercise: Defining and Applying permissions using RBAC'

# Do not change these variables
target='workstation'
run_as_root='true'


function lab_start {

  ocp4_print_prereq_header

  ocp4_is_cluster_up
  ocp4_login_as_admin
  ocp4_fail_if_project_exists "${this}"
  ocp4_exit_on_failure

  ocp4_print_setup_header

  ocp4_add_user_htpasswd 'admin' 'leader' 'developer' 'qa-engineer'
  ocp4_add_self_provisioing

  ocp4_print_setup_footer
}


function lab_finish {

  ocp4_print_cleanup_header

  ocp4_login_as_admin
  ocp4_delete_project "${this}"
  ocp4_delete_group 'dev-group' 'qa-group'
  ocp4_delete_user_htpasswd 'qa-engineer'
  ocp4_delete_user 'qa-engineer'

  ocp4_print_cleanup_footer
}


############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/${function_lib}
source /usr/local/lib/labtool.do280.shlib

grading_main_program "$@"
